[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/merkle-tree=lib/merkle-tree",
    "solady/=lib/solady",
    "@openzeppelin/contracts-v4.9.4=lib/openzeppelin-contracts-v4.9.4/contracts",
    "forge-std/=src/week12_Huff/huff-puzzles/lib/forge-std/src/",
    "foundry-huff/=src/week12_Huff/huff-puzzles/lib/foundry-huff/src",
]

gas_reports = ["*"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
